enum {
	_LIGHT_TYPE_OMNI = 0,
	_LIGHT_TYPE_SPOT = 1,
	_LIGHT_TYPE_SPOTRECT = 2,
	_LIGHT_TYPE_DISTANT = 3,
	_LIGHT_TYPE_PARALLEL = 4,
	_LIGHT_TYPE_PARSPOT = 5,
	_LIGHT_TYPE_PARSPOTRECT = 6,
	_LIGHT_TYPE_TUBE = 7,
	_LIGHT_TYPE_AREA = 8,
	_LIGHT_TYPE_PHOTOMETRIC = 9,
};

enum {
	_MATERIAL_CHANNEL_FIRST = 0,
	_MATERIAL_CHANNEL_COLOR = _MATERIAL_CHANNEL_FIRST,
	_MATERIAL_CHANNEL_REFLECTION,
	_MATERIAL_CHANNEL_TRANSPARENCY,
	_MATERIAL_CHANNEL_BUMP,
	_MATERIAL_CHANNEL_LUMINANCE,
	_MATERIAL_CHANNEL_COUNT
};
